name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package and release to GitHub
        uses: BigWigsMods/packager@v2
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
